import os

TOKEN_GOHDA = os.getenv('ACCESS_TOKEN_GOHDA')
TOKEN_ZAIM = os.getenv('ACCESS_TOKEN_ZAIM')
GIF_CHANNEL_ID = os.getenv('GIF_CHANNEL_ID')
QUOTE_CHANNEL_ID = os.getenv('QUOTE_CHANNEL_ID')
VN_TL_CHANNEL_ID = os.getenv('VN_TL_CHANNEL_ID')
VG_RELEASES_CHANNEL_ID = os.getenv('VG_RELEASES_CHANNEL_ID')
CSGO_SKINS_NEWS_CHANNEL_ID = os.getenv('CSGO_SKINS_NEWS_CHANNEL_ID')
CRYPTO_ETF_NEW_CHANNEL_ID = os.getenv('CRYPTO_ETF_NEW_CHANNEL_ID')

TENOR_API_KEY = os.getenv('TENOR_API_KEY')
HUGGING_FACE_API_KEY = os.getenv('HUGGING_FACE_API_KEY')

REDDIT_CLIENT_ID = os.getenv('REDDIT_CLIENT_ID')
REDDIT_CLIENT_SECRET = os.getenv('REDDIT_CLIENT_SECRET')

OWNER_ID = os.getenv('OWNER_ID')
ZBIYEB_ID = os.getenv('ZBIYEB_ID')
GOHDA_ID = os.getenv('GOHDA_ID')
ZAIM_ID = os.getenv('ZAIM_ID')
GUILD_ID = os.getenv('GUILD_ID')
MEMBER_LIST = os.getenv('MEMBERS_LIST')

GIF_DELAY = 10
QUOTE_DELAY = 60 * 60 * 60
VG_VN_MESSAGE_DELAY = 604800