SEARCH_TERM_LIST = [
    'umineko',
    'subahibi',
    'muramasa',
    'takuji',
    '2fap4u',
    'fate stay night',
    'steins gate',
    'totono',
    'saya no uta',
    'ever17',
    'ai the somnium file',
    'tsukihime',
    'higurashi',
    'majikoi',
    'grisaia',
    'little busters',
    'maitetsu',
    'chaos child',
    'muv-luv',
    'g-senjou no maou',
    'sharin no kuni',
    'atri',
    '428 shibuya scramble',
    'baldr sky',
    'dies irae',
    'rewrite',
    'air',
    'kanon',
    'zero escape',
    'nekopara',
    'yume miru kusuri',
    'aokana',
    'root double',
    'narcissu',
    'raging loop',
    'phoenix wright'
]
